
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
        - name: webapp
          image: luebken/todos:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:mysecretpassword@postgres/todos?sslmode=disable
---
apiVersion: v1
kind: Service
metadata:
  name: todos
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: todos
