
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
  namespace: todos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
        - name: webapp
          image: luebken/todos:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:mysecretpass_1@todos2.c7sqmiwamy4g.eu-west-2.rds.amazonaws.com/todos
      nodeSelector:
        cloud-provider: aws
---
apiVersion: v1
kind: Service
metadata:
  name: todos
  namespace: todos
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: todos
